<?php

// Labels used for different portions of the plugin
$labels = array();
$labels['activate'] = 'Require 2-Step Verification during login';
$labels['twofactor_gauthenticator'] = '2-Step Verification';
$labels['code'] = 'Verification Code';

$labels['two_step_verification_form'] = 'Verification Code';

$labels['secret'] = 'Secret';
$labels['qr_code'] = 'QR Code';
$labels['msg_infor'] = 'You can add a <i>secret</i> generated with <a href="https://code.google.com/p/google-authenticator/" target="_blank">google-authenticator</a> or generate one here.';

$labels['show_secret'] = 'Show secret';
$labels['hide_secret'] = 'Hide secret';
$labels['create_secret'] = 'Create secret';

$labels['show_qr_code'] = 'Show QR Code';
$labels['hide_qr_code'] = 'Hide QR Code';

$labels['recovery_codes'] = 'Recovery codes';
$labels['show_recovery_codes'] = 'Show recovery codes';
$labels['hide_recovery_codes'] = 'Hide recovery codes';

$labels['setup_all_fields'] = 'Setup all fields (needs Save)';

$labels['enrollment_dialog_title'] = '2-Step Verification';
$labels['enrollment_dialog_msg'] = '<strong>2-Step Verification</strong> is required for safety, please configure.';

$labels['check_code'] = 'Test Verification Code';
$labels['code_ok'] = 'Code OK';
$labels['code_ko'] = 'Incorrect code';

// Messages used for the different portions of the plugin
$messages = array();
$messages['successfully_saved'] = '2-Step Verification settings saved.';
?>
